DROP DATABASE IF EXISTS juego;
CREATE DATABASE juego;
USE juego;

CREATE TABLE JUGADOR (
	ID INT NOT NULL,
	USUARIO VARCHAR(20) NOT NULL,
	CONTRASEÑA VARCHAR(30),
	PARTIDASGANADAS INT,
	PARTIDASJUGADAS INT,
	PRIMARY KEY (ID)
)ENGINE=InnoDB;

CREATE TABLE PARTIDAS (
	ID INT NOT NULL,
	ID_G INT NOT NULL,
	DURACION INT,
	MEJORJUGADA INT,
	FECHA VARCHAR(20),
	HORA VARCHAR(10),
	FOREIGN KEY (ID_G) REFERENCES JUGADOR(ID),
	PRIMARY KEY (ID)
)ENGINE=InnoDB;

INSERT INTO JUGADOR VALUES (1,'INGRID','AAA',15,25);
INSERT INTO JUGADOR VALUES (2,'ALEIX','BBB',7,14);
INSERT INTO JUGADOR VALUES (3,'DANI','CCC',5,9);

INSERT INTO PARTIDAS VALUES (1,2,14,3,'11/03/2021','10:30');
INSERT INTO PARTIDAS VALUES (2,3,16,4,'10/03/2021','14:30');
INSERT INTO PARTIDAS VALUES (3,1,13,5,'09/03/2021','11:30');



